package View;

public class tela_GUI extends javax.swing.JFrame {

    public static String senha = "";
    
    public tela_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PainelPreferencial_jpl = new javax.swing.JPanel();
        MsgPreferencial_lbl = new javax.swing.JLabel();
        PaineNãolPreferencial_jpl = new javax.swing.JPanel();
        MsgNaoPreferencial_lbl = new javax.swing.JLabel();
        Preferencial_lbl = new javax.swing.JLabel();
        NaoPreferencial_lbl = new javax.swing.JLabel();
        SenhaNaoPreferêncial_btn = new javax.swing.JButton();
        Sair_bnt = new javax.swing.JButton();
        Preferêncial_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        MsgPreferencial_lbl.setBackground(new java.awt.Color(255, 255, 255));
        MsgPreferencial_lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MsgPreferencial_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PainelPreferencial_jplLayout = new javax.swing.GroupLayout(PainelPreferencial_jpl);
        PainelPreferencial_jpl.setLayout(PainelPreferencial_jplLayout);
        PainelPreferencial_jplLayout.setHorizontalGroup(
            PainelPreferencial_jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPreferencial_jplLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MsgPreferencial_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PainelPreferencial_jplLayout.setVerticalGroup(
            PainelPreferencial_jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPreferencial_jplLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MsgPreferencial_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(PainelPreferencial_jpl);
        PainelPreferencial_jpl.setBounds(50, 90, 100, 170);

        MsgNaoPreferencial_lbl.setBackground(new java.awt.Color(255, 255, 255));
        MsgNaoPreferencial_lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MsgNaoPreferencial_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout PaineNãolPreferencial_jplLayout = new javax.swing.GroupLayout(PaineNãolPreferencial_jpl);
        PaineNãolPreferencial_jpl.setLayout(PaineNãolPreferencial_jplLayout);
        PaineNãolPreferencial_jplLayout.setHorizontalGroup(
            PaineNãolPreferencial_jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineNãolPreferencial_jplLayout.createSequentialGroup()
                .addComponent(MsgNaoPreferencial_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PaineNãolPreferencial_jplLayout.setVerticalGroup(
            PaineNãolPreferencial_jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MsgNaoPreferencial_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        jPanel1.add(PaineNãolPreferencial_jpl);
        PaineNãolPreferencial_jpl.setBounds(220, 90, 100, 170);

        Preferencial_lbl.setBackground(new java.awt.Color(204, 204, 204));
        Preferencial_lbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Preferencial_lbl.setText("Preferêncial");
        Preferencial_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Preferencial_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Preferencial_lbl);
        Preferencial_lbl.setBounds(60, 50, 110, 40);

        NaoPreferencial_lbl.setBackground(new java.awt.Color(204, 204, 204));
        NaoPreferencial_lbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NaoPreferencial_lbl.setText("Não Preferêncial");
        NaoPreferencial_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NaoPreferencial_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(NaoPreferencial_lbl);
        NaoPreferencial_lbl.setBounds(220, 50, 120, 40);

        SenhaNaoPreferêncial_btn.setText("Não Prefenrêncial");
        SenhaNaoPreferêncial_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaNaoPreferêncial_btnActionPerformed(evt);
            }
        });
        jPanel1.add(SenhaNaoPreferêncial_btn);
        SenhaNaoPreferêncial_btn.setBounds(210, 30, 120, 23);

        Sair_bnt.setText("Sair");
        Sair_bnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_bntActionPerformed(evt);
            }
        });
        jPanel1.add(Sair_bnt);
        Sair_bnt.setBounds(280, 280, 70, 23);

        Preferêncial_btn.setText("Prefenrêncial");
        Preferêncial_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preferêncial_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Preferêncial_btn);
        Preferêncial_btn.setBounds(40, 30, 120, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(376, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Sair_bntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair_bntActionPerformed
       System.exit(0);
    }//GEN-LAST:event_Sair_bntActionPerformed

    private void SenhaNaoPreferêncial_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaNaoPreferêncial_btnActionPerformed
        
            
        

    }//GEN-LAST:event_SenhaNaoPreferêncial_btnActionPerformed

    private void Preferêncial_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preferêncial_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preferêncial_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MsgNaoPreferencial_lbl;
    private javax.swing.JLabel MsgPreferencial_lbl;
    private javax.swing.JLabel NaoPreferencial_lbl;
    private javax.swing.JPanel PaineNãolPreferencial_jpl;
    private javax.swing.JPanel PainelPreferencial_jpl;
    private javax.swing.JLabel Preferencial_lbl;
    private javax.swing.JButton Preferêncial_btn;
    private javax.swing.JButton Sair_bnt;
    private javax.swing.JButton SenhaNaoPreferêncial_btn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
